# Generated by Django 5.1.6 on 2025-02-13 23:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('file', models.FileField(upload_to='csv_files/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléchargement')),
                ('last_viewed', models.DateTimeField(blank=True, null=True, verbose_name='Dernière consultation')),
                ('view_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('operations_log', models.JSONField(blank=True, default=list, verbose_name='Journal des opérations')),
                ('rows_count', models.IntegerField(default=0, verbose_name='Nombre de lignes')),
                ('columns_count', models.IntegerField(default=0, verbose_name='Nombre de colonnes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Fichier CSV',
                'verbose_name_plural': 'Fichiers CSV',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='csv_processor.csvfile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
