# Generated by Django 5.1.3 on 2024-11-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_processor', '0002_delete_processeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='columns_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='rows_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
