# Generated by Django 5.1.3 on 2024-11-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_processor', '0003_csvfile_columns_count_csvfile_rows_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='processed',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='operations_log',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
