# Generated by Django 5.1.3 on 2024-11-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_processor', '0004_remove_csvfile_processed_csvfile_last_viewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
