# Generated by Django 5.1.3 on 2024-11-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_processor', '0005_alter_csvfile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='columns_count',
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='rows_count',
        ),
    ]
