# Generated by Django 5.1.3 on 2024-11-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_processor', '0006_remove_csvfile_columns_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='columns_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='rows_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='operations_log',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
