# Generated by Django 5.1.3 on 2024-11-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_processor', '0007_csvfile_columns_count_csvfile_rows_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='operations_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
