# Generated by Django 5.1.3 on 2024-12-09 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_processor', '0008_alter_csvfile_operations_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Fichier CSV', 'verbose_name_plural': 'Fichiers CSV'},
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='columns_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de colonnes'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to='csv_files/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière consultation'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='operations_log',
            field=models.JSONField(blank=True, default=list, verbose_name='Journal des opérations'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='rows_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de lignes'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de téléchargement'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de vues'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='csv_processor.csvfile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
